### ISSUE TITLE
How to set the input 1-2 characters can appear to complement the menu

### ISSUE THREAD

**Issue by iuunhao** [roxma/nvim-completion-manager#104]
How to set the input 1-2 characters can appear to complement the menu, of course has done very perfect.

**Comment by roxma** [comment]
I don't understand what you mean.

Can you elaborate?

**Comment by iuunhao** [comment]
I found that in the CSS file, you must enter three characters to appear prompt menu, how to customize, you must enter three characters restrictions? For example, 1 characters and 4 characters can display menus.

**Comment by roxma** [comment]
`:help g:cm_refresh_length`
