### ISSUE TITLE
排序问题

### ISSUE THREAD

**Issue by Cosson2017** [roxma/nvim-completion-manager#114]
@roxma 
请问大神：
    开启模糊匹配的时候，候选项是按照字母序排序的，怎样设置能按照匹配度排序？

**Comment by roxma** [comment]
https://github.com/roxma/nvim-completion-manager/blob/master/pythonx/cm_matchers/fuzzy_matcher.py

The fuzzy matcher does not sort by alphabet. But the algorithm for score is sub-optimal. 

You could share your idea on improving it.
