### ISSUE TITLE
HTML completion

### ISSUE THREAD

**Issue by asilvadesigns** [roxma/nvim-completion-manager#115]
How does one register omnifunc as a source for html completion...

**Comment by roxma** [comment]
Please refer to the css version described in the README. `:help cm#register_source()` for more information.

Post your minimal vimrc if you're having trouble integrating omnifunc.

**Comment by joanasleet** [comment]
I tried to adapt the css example:
```vim
au User CmSetup call cm#register_source({'name' : 'cm-html',
        \ 'priority': 9, 
        \ 'scopes': ['html'],
        \ 'scoping': 1,
        \ 'abbreviation': 'html',
        \ 'cm_refresh_patterns':['\w{2,}$',':\s+\w*$'],
        \ 'cm_refresh': {'omnifunc': 'htmlcomplete#CompleteTags'},
        \ })
```
`omnifunc` is set to `htmlcomplete#CompleteTags`
What am I doing wrong ? Is there an option to try `omnifunc` by default if other sources don't yield results ?
