### ISSUE TITLE
Add support for ujihisa/neco-look.

### ISSUE THREAD

**Issue by katsika** [roxma/nvim-completion-manager#121]
Would that be possible to add support for [ujihisa/neco-look](https://github.com/ujihisa/neco-look) plugin? I use neco-look in text and mail filetypes and found it very useful. Thanks.

**Comment by roxma** [comment]
Duplicated with #90 

There's code sample at https://github.com/roxma/nvim-completion-manager/issues/90#issuecomment-309115218 .

I'm not sure whether @257 has continued the work. But it's already working the last time I test it.
