### ISSUE TITLE
Problem with Ultisnips expand.

### ISSUE THREAD

**Issue by katsika** [roxma/nvim-completion-manager#122]
I have configured:

    let g:UltiSnipsExpandTrigger = "<Plug>(ultisnips_expand)"
    inoremap <silent> <c-u> <c-r>=cm#sources#ultisnips#trigger_or_popup("\<Plug>(ultisnips_expand)")<cr>

as per https://github.com/roxma/nvim-completion-manager/issues/12#issuecomment-278605326.

But every time I hit C-u in empty buffer (in insert mode) instead of getting snippets list I get following error:

    Error detected while processing function 
    cm#sources#ultisnips#trigger_or_popup[12]..cm#sources#ultisnips#cm_refresh:
    line   25:
    E716: Key not present in Dictionary: startcol

When there is text before cursor, `foldp` for instance, instead of snippet expansion I get  `foldp<Plug>(ultisnips_expand)` inserted unto buffer.

Is there a bug or is it down to my set up?

**Comment by roxma** [comment]
Fixed by https://github.com/roxma/nvim-completion-manager/commit/72e1eb472f0561ee80185a32d54e1b2d72efb8a7

**Comment by katsika** [comment]
Works perfectly, thank you!
