### ISSUE TITLE
NCM disabled for buftype != '' by default.

### ISSUE THREAD

**Issue by katsika** [roxma/nvim-completion-manager#124]
I understand that https://github.com/roxma/nvim-completion-manager/blob/master/autoload/cm.vim#L599 disables completion plugin completely unless buftype is ''. I would like to use completions in https://github.com/jreybert/vimagit buffer, which has value of `acwrite` set by https://github.com/jreybert/vimagit/blob/3b61de8d4611814d02317f187fae23d118b3f69e/plugin/magit.vim#L1128.

Do you think it would make sense to provide a configurable whitelist of some sort to allow users configure buffer types they wish to have completions for?

**Comment by roxma** [comment]
You could call `cm#enable_for_buffer()` explicitly. NCM will not override it after that.

**Comment by katsika** [comment]
It does the job, thank you very much!
