### ISSUE TITLE
Ctrl-L broken

### ISSUE THREAD

**Issue by SevereOverfl0w** [roxma/nvim-completion-manager#127]
With auto-completion menu, Ctrl-L seems to not work. It works if I do `<C-x><C-o>` and then hit `<C-l>`.

Very frustrating for long completions with common prefix.

**Comment by roxma** [comment]
Try this option: `let g:cm_completekeys = "\<Plug>(cm_omnifunc)"`

NCM will use `omnifunc` instead of the `complete()` call.

**Comment by roxma** [comment]
Just notice `<c-l>` is also breaken for non-prefix match.

**Comment by SevereOverfl0w** [comment]
I think this workaround also causes minimum number of characters to be ignored.

**Comment by roxma** [comment]
> I think this workaround also causes minimum number of characters to be ignored.

Could you elaborate?

**Comment by SevereOverfl0w** [comment]
I cannot seem to reproduce that behaviour now. I was somehow getting completion for, e.g. `+`. Will let you know if it happens again.
