### ISSUE TITLE
SnipMate won't expand if there are multiple options

### ISSUE THREAD

**Issue by boardfish** [roxma/nvim-completion-manager#131]
Tried the fix in someone else's issue with UltiSnips (#89), but it's not working. When I press the enter key, a newline is created rather than expanding the snippet selected. Tested in Ruby with the def method.

**Comment by roxma** [comment]
I'll need the minimal vimrc, and steps to reproduce this issue.

**Comment by boardfish** [comment]
### Steps

nvim test.rb
`idef<TAB>`

### Result

Many other potential snippets appear, such as 'deft'. You can tab through them but pressing `ENTER` results in a newline (with the right indent for a def block, strangely).

```
if has('nvim')
    let s:editor_root=expand("~/.config/nvim")
else
    let s:editor_root=expand("~/.vim")
endif
let mapleader="\<SPACE>"
let g:python_host_prog = '/home/si/.pyenv/versions/general/bin/python'
let g:python3_host_prog = '/home/si/.pyenv/versions/neovim3/bin/python'
set shell=/bin/bash

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" set the backup directory so we don't get weird tilde files...
" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

" The following are examples of different formats supported.
" Keep Plugin commands between vundle#begin/end.
" plugin on GitHub repo
Plugin 'garbas/vim-snipmate'
imap <expr> <CR>  (pumvisible() ?  "\<c-y>\<Plug>(cm_inject_snippet)\<Plug>(expand_or_nl)" : "\<CR>")
imap <expr> <Plug>(expand_or_nl) (has_key(v:completed_item,'snippet')?"\<C-U>":"\<CR>")
Plugin 'roxma/nvim-completion-manager'
" Optional:
Plugin 'honza/vim-snippets'
"Fix for not appearing until i create a new split
set laststatus=2

" All of your Plugins must be added before the following line
call vundle#end()            " required
syntax on
filetype plugin indent on    " required
``

**Comment by roxma** [comment]
> SnipMate depends on vim-addon-mw-utils and tlib.

I can't find it in your vimrc.

**Comment by boardfish** [comment]
Oh, must've overlooked including it in the trimmed .vimrc. It's definitely in my init.vim.

**Comment by roxma** [comment]
It is fixed. Use this version instead. The previous version may work, but it is deprecated.

Suppose you use the `<c-u>` key for expanding snippet:

```vim
imap <expr> <CR>  (pumvisible() ?  "\<c-y>\<Plug>(expand_or_nl)" : "\<CR>")
imap <expr> <Plug>(expand_or_nl) (cm#completed_is_snippet() ? "\<C-U>":"\<CR>")
```

**Comment by boardfish** [comment]
E117: Unknown function: cm#completed_is_snippet
There's another error after that. Zero record of the function existing in the plugin after I grepped the whole directory with `grep -rnw '/home/si/.vim/bundle/nvim-completion-manager/' -e 'cm\#snippet' and 'cm\#complete' and 'cm\#completed_is_snippet'.

**Comment by roxma** [comment]
have you pull the newest version?

**Comment by boardfish** [comment]
I did just now. It no longer errors, but deletes what was written beforehand entirely. Same test circumstances, `idef<Tab><Enter>` results in the word 'def' that was previously written being deleted.

**Comment by roxma** [comment]
Something like `imap <c-u> <Plug>snipMateTrigger`

You need to read the snipMate doc.
