### ISSUE TITLE
Python- docstring window option?

### ISSUE THREAD

**Issue by bbkane** [roxma/nvim-completion-manager#132]
Is there a way to display the docstring for Python in the preview window similar to Jedi: 

![the docstring window on top](https://github.com/davidhalter/jedi/raw/master/docs/_screenshots/screenshot_function.png)

[the link to disable the feature in jedi-vim](https://github.com/davidhalter/jedi-vim#i-dont-want-the-docstring-window-to-popup-during-completion)

**Comment by roxma** [comment]
`:help g:cm_completeopt`

Add `preview` into this option. Note that you need to add some code to close the window automatically.

**Comment by bbkane** [comment]
Thanks, that was just what I needed! Adding this code for others (stolen from jedi-vim's implementation) to close the preview window when insert mode is left.

```vim
    Plug 'roxma/nvim-completion-manager'
    " Add preview to see docstrings in the complete window.
    let g:cm_completeopt = 'menu,menuone,noinsert,noselect,preview'

    " Close the prevew window automatically on InsertLeave
    " https://github.com/davidhalter/jedi-vim/blob/eba90e615d73020365d43495fca349e5a2d4f995/ftplugin/python/jedi.vim#L44
    augroup ncm_preview
        autocmd! InsertLeave <buffer> if pumvisible() == 0|pclose|endif
    augroup END
```
