### ISSUE TITLE
Add TypeScript support

### ISSUE THREAD

**Issue by zaferot** [roxma/nvim-completion-manager#139]
Hello here. Are there any plans to add TypeScript source?
There is a good candidate for being as a source plugin: [nvim-typescript](https://github.com/mhartington/nvim-typescript). It already supports deoplete.

Thanks!

**Comment by roxma** [comment]
https://github.com/mhartington/nvim-typescript/issues/45

I have no plan currently. I don't have enough time.

**Comment by prabirshrestha** [comment]
@zaferot You should give language server protocol a try. https://github.com/prabirshrestha/typescript-language-server or https://github.com/sourcegraph/javascript-typescript-langserver

And use https://github.com/autozimu/LanguageClient-neovim or https://github.com/prabirshrestha/vim-lsp.

Besides completions you get lot of other features for free like goto definition, rename symbols, find all references and so on.

**Comment by zaferot** [comment]
@prabirshrestha Thanks! I'll give it a try.

**Comment by roxma** [comment]
https://github.com/mhartington/nvim-typescript/pull/81
