### ISSUE TITLE
Disable ~cwd in file path completion

### ISSUE THREAD

**Issue by kristijanhusak** [roxma/nvim-completion-manager#140]
Hi,

how can i disable `~cwd` suggestions when doing file path completion? It gives me too much suggestion that i don't want to use here. Here's an example:

![screenshot](https://i.imgur.com/msdFZcn.png)

I don't want to see `api`, `app` and `web` here.

Edit: Also, is there a way to remove or shorten the autocomplete menu source? Example:

![screenshot2](https://i.imgur.com/SHGMIhX.png)

I would like to remove `Tag: lib/infrastructure/cache/memory_cache.js`, or at least shorten it to `Tag` or  something like that.

Thanks!

**Comment by roxma** [comment]
Unfortunately they're not customizable currently.

Possible solution:

- Add custom filter support, then you could write custom script to filter/modify results.

**Comment by kristijanhusak** [comment]
Should i write that on python or vimscript level?

**Comment by roxma** [comment]
It should be python, for async.

**Comment by roxma** [comment]
Switching to ncm2 https://github.com/ncm2/ncm2, I think https://github.com/ncm2/ncm2-highprio-pop kind of solves this issue.

Closing
