### ISSUE TITLE
Which repo should I use for PHP completion?

### ISSUE THREAD

**Issue by rawaludin** [roxma/nvim-completion-manager#144]
I see there's 2 repo for PHP completion, I successfully installed both LanguageServer-php-neovim and ncm-phpactor.

But, which should I use? What's the different? Or, should I just use both for best completion?

**Comment by roxma** [comment]
They're based on different engine. I don't know much about the differences. 

phpactor currently doesn't have variable completion.

You could pick one randomly, then try another one when you find that the first one doesn't feed you need.
