### ISSUE TITLE
Language specific completion for reStructuredText?

### ISSUE THREAD

**Issue by ashfinal** [roxma/nvim-completion-manager#145]
I saw your [scoping sources for Markdown](https://github.com/roxma/nvim-completion-manager#scoping-sources), it is really handy for writing blog. But recently I turn to [reStructuredText](http://docutils.sourceforge.net), I'm wondering is there any way to make language completion work in reStructuredText document?

reST document's filetype is `rst`, and its code block is like this:
```rst
Normal paragraph.

.. code:: python
   import sys
   print(sys.version)

Normal paragraph.
```
Thanks for your help in advance.

**Comment by roxma** [comment]
Just added reStructuredText support.

Though, current version cannot strip the indentation of the code block for completion sources. Fortunately, it still works for python.

**Comment by ashfinal** [comment]
Just gave it a try and it works. Wonderful!
Thanks for your help, making ncm a better plugin. ❤️
