### ISSUE TITLE
High resource consumption

### ISSUE THREAD

**Issue by zackhsi** [roxma/nvim-completion-manager#147]
The python completer is using a full core. This happened after waking my laptop in the morning.

<img width="829" alt="screen shot 2017-10-17 at 8 42 54 am" src="https://user-images.githubusercontent.com/806101/31676379-4ba149a2-b31c-11e7-8428-58ec772a2c4a.png">

`dtruss` shows the syscall count as:
```
CALL                                        COUNT
munmap                                         86
mmap                                          131
```

I recorded a trace via Instruments, but didn't get anything new out of it.

Any ideas what could have caused this? During normal operation, this does not happen.

**Comment by roxma** [comment]
Similar issue #62

I believe this is upstream issue. // cc @davidhalter

That's why only jedi source is running as a standalone process.

Maybe we need more workarounds. Like auto restarting the process when there's no edit activity for a while.

**Comment by roxma** [comment]
// cc @theFool32

**Comment by davidhalter** [comment]
There might still be issues in jedi `0.11.0`, I'm not sure. If you can reproduce it, please open an issue. This was definitely an issue in `0.10.2`, so if your jedi version is that old, please upgrade.

**Comment by zackhsi** [comment]
Can't repro. Will update if that becomes the case.
