### ISSUE TITLE
Error when I wrote Chinese character in python file

### ISSUE THREAD

**Issue by Crisirf** [roxma/nvim-completion-manager#148]
* **platform**: windows10
* **vim version**: vim 8.596
* and with both newest nvim-completion-manager and vim-hug-neovim-rpc .

It is 100% appear on my machine.
Have you ever had the same situation?

**Comment by roxma** [comment]
What error? 

Could you post more informaton, including the reproducing steps.

I don't have a Windows currently, and I cannot reproduce it on my vim8.

**Comment by Crisirf** [comment]
@roxma 
Thanks for your reply.

To reproduce this bug:
1. A new python file.
2. Wrote a Chinese character, and i got it.

 en.  There are a lot of words in log file, and I can't catch the point.
 Or I send the log file to your email?

**Comment by roxma** [comment]
Use gist or paste bin for pasting log file.

**Comment by Crisirf** [comment]
Like this [log](https://gist.github.com/Crisirf/f0049290b40c751a39a829039a30fa99) ?

**Comment by roxma** [comment]
What's the error shown on the screen?

I also need the result of `set encoding` and `set fileencoding` after you openning the buffer

**Comment by roxma** [comment]
I can reproduce the error on my laptop with `set encoding=cp936`

![screenshot_20171018_174134](https://user-images.githubusercontent.com/4538941/31711741-aec08056-b42b-11e7-97a3-deca97538d2b.png)

vimrc:

```vim
    set nocompatible
    syntax on
    filetype plugin indent on
    set encoding=utf-8 fileencodings=ucs-bom,utf-8,gbk,gb18030,latin1 termencoding=utf-8

    call plug#begin(expand('<sfile>:h') . '/plugged/')
    Plug 'roxma/nvim-completion-manager'
        if !has('nvim')
            Plug 'roxma/vim-hug-neovim-rpc'
        endif
    call plug#end()
    set encoding=cp936
```

It's working fine with `set encoding=utf-8`

**Comment by Crisirf** [comment]
* encoding=utf-8
* fileencoding=utf-8

The screen:
![1](http://chuantu.biz/t6/102/1508319480x3063298882.png)
\   
![2](http://chuantu.biz/t6/102/1508319814x3063298882.png)

vimrc:
```viml
    set nocompatible
    set encoding=utf-8

    set fileencoding=utf-8
    set fileencodings=utf8,cp936,ucs-bom,latin1,chinese

    call plug#begin('$VIM/vimfiles/plugged')
    Plug 'roxma/nvim-completion-manager'
    if !has('nvim')
        Plug 'roxma/vim-hug-neovim-rpc'
    endif
    call plug#end()
```

But I can't reproduce the error with the mini vimrc. It seems other setting caused it, I'll check my configuration, And test it on mac. 

thanks for you help.

**Comment by roxma** [comment]
It's wierd that python is executing code in `encodings\cp1252.py`

**Comment by roxma** [comment]
What's the result of `:python3 print(sys.getdefaultencoding())`?

**Comment by roxma** [comment]
Interesting:

```
>>> "\u86e4"
'蛤'
>>> "\u86e4".encode('cp1252')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/rh/rh-python35/root/usr/lib64/python3.5/encodings/cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode character '\u86e4' in position 0: character maps to <undefined>
```

**Comment by roxma** [comment]
My guess: install python 3.6 or higher will fix this issue.

**Comment by Crisirf** [comment]
* `:python3 print(sys.getdefaultencoding())` => utf-8
* `:python3 print(sys.getfilesystemencoding())` => mbcs
* `:python3 import locale; print(locale.getpreferredencoding())` => cp1252

It works fine on Mac.

**Comment by roxma** [comment]
The screenshot you posted is triggered by logging. 

What does it look like without enabling logging?

**Comment by Crisirf** [comment]
Oh, I can't reproduce the bug now.

**Comment by Crisirf** [comment]
It seems caused by logging, 
When I re-enable the logging configuration of NCM, It repeared again.

And shown logging error : ![](https://camo.githubusercontent.com/0200205568b6d6898ff42e391fb7c19a7a350627/687474703a2f2f636875616e74752e62697a2f74362f3130322f3135303833313934383078333036333239383838322e706e67)

**Comment by roxma** [comment]
Ok. Update vim-hug-neovim-rpc to the latest version.

And let's wait for the next release of neovim python client. // https://github.com/neovim/python-client/pull/276

// cc @justinmk
