### ISSUE TITLE
refine the css omnifunc

### ISSUE THREAD

**Issue by wangsongiam** [roxma/nvim-completion-manager#15]
First of all, thanks for the great work, best Vim completion I've tried so far. Shout out to "Made in China"

Seconded, can we refined the CSS completion with a `;` in the end? You know typically we don't want to type that when making an autocompletion in CSS.

*Expecting(from Atom editor):*
![2017-02-13 02 30 22](https://cloud.githubusercontent.com/assets/19645990/22874548/a8d256c4-f194-11e6-9db9-ab44662b1068.gif)

*Now in Neovim:*
![2017-02-13 02 31 02](https://cloud.githubusercontent.com/assets/19645990/22874562/c1839174-f194-11e6-874a-47bb2d74b77d.gif)

**Comment by roxma** [comment]
I  feel kindof  in-consistent by not completing the  `;` character too.

However, this is the behavior of neovim [csscomplete.vim](https://github.com/neovim/neovim/blob/master/runtime/autoload/csscomplete.vim), provided by [project csscomplete.vim](https://github.com/othree/csscomplete.vim/blob/master/autoload/csscomplete.vim).

You might need to post an issue there.

**Comment by roxma** [comment]
FYI, I've opened an issue on [csscomplete.vim/issues/6](https://github.com/othree/csscomplete.vim/issues/6)

**Comment by roxma** [comment]
hi, @wangsongiam 

I get notified that [csscomplete.vim](https://github.com/othree/csscomplete.vim)  gets updated for this, thanks to @othree.

@wangsongiam try install install the latest version of csscomplete.vim, have fun with it

**Comment by wangsongiam** [comment]
Awesome, thank you so much! 👍
