### ISSUE TITLE
Limit number of candidates?

### ISSUE THREAD

**Issue by Alok** [roxma/nvim-completion-manager#151]
In some files, completion menus take up the whole page, which I never want. Is there a way to limit the number of candidates shown?

Basically, `g:deoplete#max_list` for NCM.

**Comment by roxma** [comment]
Why not setting the pumheight option?

**Comment by liuchengxu** [comment]
Yes, @Alok , you can simply `set pumheight=20` (change 20 to whatever you like), then the popup menu will not occupy the full screen. See `:h 'pumheight'`.
