### ISSUE TITLE
How to complete for python2 modules?

### ISSUE THREAD

**Issue by Ninlives** [roxma/nvim-completion-manager#158]
I'm working on MacOS and installed both python2 and python3 via Homebrew. They all can be found in the PATH, but when I editing a .py file nom always try to complete for python3 and ignore those python2 modules, so how could I switch to python2 completion?

**Comment by roxma** [comment]
Currently python2 completion is only available when you're running on virtual env.

Activate the virtual env of your python2 project before starting neovim.
