### ISSUE TITLE
Support additionalTextEdits

### ISSUE THREAD

**Issue by DeltaEvo** [roxma/nvim-completion-manager#159]
Related https://github.com/autozimu/LanguageClient-neovim/issues/85

LanguageClient-neovim alrealy pass `additionalTextEdits` to nvim-completion-manager so I would be awesome if ncm could use this information

**Comment by roxma** [comment]
Duplicate #130 

It should be executed by a snippet engine, so that NCM won't add  any new key binding.

I've been busy. There's no ETA.
