### ISSUE TITLE
E716: No se encuentra la llave en el diccionario. path

### ISSUE THREAD

**Issue by santiagodoldan** [roxma/nvim-completion-manager#16]
Hello,

First of all thanks for this nice plugin 💪 

I'm getting this error `E716: No se encuentra la llave en el diccionario. path`, here you have the line 👉 https://github.com/roxma/nvim-completion-manager/blob/master/autoload/cm.vim#L299

Cheers

**Comment by roxma** [comment]
Hi, @santiagodoldan 

I've updated the plugin, please confirm that this issue is fixed

**Comment by santiagodoldan** [comment]
Yep, it's working fine now, thanks
