### ISSUE TITLE
Plugin breaks when files are in a symlinked directory

### ISSUE THREAD

**Issue by curioussavage** [roxma/nvim-completion-manager#160]
On my machine `.config/nvim` and `.vim` directories are symlinks to a place I keep all my dotfiles. This is the first plugin that has not worked due to that.

![screen shot 2017-11-21 at 8 51 33 am](https://user-images.githubusercontent.com/7064600/33085310-37951964-ce99-11e7-83b5-ccc6f8563bb6.png)

**Comment by roxma** [comment]
Hmm...

I have symlink on my system too...

**Comment by roxma** [comment]
I think your rtp has multiple `nvim-completion-manager`. 

check your rtp by `:echo &rtp`

**Comment by curioussavage** [comment]
You are probably right. I removed copied the files there and it was still broken. Ill have to confirm monday since I'm out for the holiday and its my work computer.
