### ISSUE TITLE
Unwanted auto-complete issue

### ISSUE THREAD

**Issue by Ron89** [roxma/nvim-completion-manager#17]
The auto-trigger of the complete menu while typing is useful, but when it automatically choose the first match when the thing I want to type is not even in the list, the autocomplete would be quite annoying.

Even when I use backspace, the erasing action will trigger the menu again and what is erased would pop back again.

**Comment by roxma** [comment]
The `completeopt` should be set by the plugin, did you override it somehow?

```
set completeopt=menu,menuone,noinsert,noselect
```

https://github.com/roxma/nvim-completion-manager/blob/master/autoload/cm.vim#L47

**Comment by roxma** [comment]
I'm not sure I understand what you mean, I would appreciate it if you post a screencast

**Comment by Ron89** [comment]
I do have `set completeopt=menu,preview` in my vimrc. Though I don't think it should be able to overwite your setting since vimrc is loaded earlier than plugins, the lack of `noinsert` and `noselect` is definitely what causes the issue.
 
Thanks, I'll try it again some time.

**Comment by roxma** [comment]
Hi, I've updated the plugin for this 
you may try again and see if the issue still exist
