### ISSUE TITLE
documentation: roxma/vim-hug-neovim-rpc should start before nvim-completion-manager

### ISSUE THREAD

**Issue by blablablerg** [roxma/nvim-completion-manager#170]
Hello,

From the documentation (also on the frontpage), when using VIM8, it is not clear that you should start vim-hug-neovim-rpc before nvim-completion-manager. Because this requirement is listed later in the documentation, I thought it vim-hug-neovim-rpc should start after ncm. 

It might be obvious for someone experienced, but for a novice like me it took more than a day to figure out why it wasnt working!

**Comment by roxma** [comment]
If you have both plugin installed, they should just works.

I'm closing. The issue description is unclear and this repo is deprecated.
