### ISSUE TITLE
Rust ultisnips argument expansion not working with LanguageClient-neovim

### ISSUE THREAD

**Issue by rusterize** [roxma/nvim-completion-manager#172]
@roxma, thank you for such a good work with this completion engine, it might take over all the other ones with the progress you are doing.

The argument expansion is not working with ultisnips in Rust, using LanguageClient-neovim:

![f](https://user-images.githubusercontent.com/32858036/34496014-c6f50e14-efc5-11e7-9bc4-151b340b551e.gif)

Some details:
* `rls-preview 0.124.0-nightly (299a6a9 2017-12-25)` via rustup
* `LanguageClient-neovim` from git via `Plug`
* `nvim-completion-manager` from git via `Plug`
* Python (builtin) with `jedi` is working fine

The problem in Rust must be a race condition, because ***one*** time it worked, and I was never able to reproduce it, even in the same session. The difference I noticed is that --when it worked-- the completion menu showed a '[+]'  after the name of the function, just like it does in python.

**Comment by YaLTeR** [comment]
I have the same issue with both RLS and the [cquery](https://github.com/jacobdufault/cquery) language server.

**Comment by LaVieEstDure** [comment]
+1, same issue but I'm using `asyncomplete.vim`, `asyncomplete-lsp.vim`, `vim-lsp` and `async.vim` instead of `LanguageClient-neovim` and `nvim-completion-manager`. Also using Plug as plugin manager.

**Comment by roxma** [comment]
known issue.

planned in ncm2.
