### ISSUE TITLE
Warning on startup, regarding `on_core_channel_error`

### ISSUE THREAD

**Issue by victorz** [roxma/nvim-completion-manager#176]
![image](https://user-images.githubusercontent.com/7494/35038975-bb417dc4-fb7c-11e7-98a6-24e62e6347ce.png)

I get the above warning when opening a python file. Transcription below.

```
Error detected while processing function <SNR>84_on_core_channel_error:
line    1:
/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/msgpack_stream.py:23: FutureWarnin
g: use_bin_type option is not specified. Default value of the option will be changed i
n future version.^@  self._packer = Packer(unicode_errors=unicode_errors_default)^@
```

I am using neovim version 0.2.2.

**Comment by Shougo** [comment]
It is neovim/python-client warning.
It should be reported here.

https://github.com/neovim/python-client
