### ISSUE TITLE
How to remap <C-n> and <C-p>?

### ISSUE THREAD

**Issue by ijsnow** [roxma/nvim-completion-manager#177]
Heyo! Great plugin. Thanks a lot!

I was just wondering how I could remap the navigating keys to something closer together like <C-j> and <C-k> or something like that.

Could you point me in the right direction?

**Comment by Shougo** [comment]
Example:

`inoremap <Tab> pumvisible()? "\<C-n>" : "\<Tab>"`
`inoremap <S-tab> pumvisible()? "\<C-p>" : "\<S-Tab>"`

**Comment by ijsnow** [comment]
Thanks, but that didn't work! I saw that in the README for mapping to tab but I couldn't translate it to other keys. I tried this so that ctl-n is reverse and ctl-m is forward to no avail:

```
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<C-m"
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<C-n"
```

**Comment by Shougo** [comment]
```vim
inoremap <expr> <C-m> pumvisible() ? "\<C-n>" : "\<C-m>"
inoremap <expr> <C-n> pumvisible() ? "\<C-p>" : "\<C-n>"
```

**Comment by ijsnow** [comment]
None of this worked for me but I got used to <C-n>/<C-p>
