### ISSUE TITLE
Only show completion popup on key

### ISSUE THREAD

**Issue by Xatenev** [roxma/nvim-completion-manager#180]
Hi,

I didn't find a way in the docs to only make the popup open on a specific key (Ctrl + Tab) for example, and **not** automatically

Thanks!

**Comment by Shougo** [comment]
https://github.com/roxma/nvim-completion-manager/blob/e724a442072261993ca503e969d2cb25722ab1d2/doc/nvim-completion-manager.txt#L302
https://github.com/roxma/nvim-completion-manager/blob/e724a442072261993ca503e969d2cb25722ab1d2/doc/nvim-completion-manager.txt#L571
