### ISSUE TITLE
`set noshowmode` showing unnecessary information

### ISSUE THREAD

**Issue by bedax** [roxma/nvim-completion-manager#182]
## Versions
**Neovim:** `0.2.3-455-gbc17ad31d` (latest as of 2018/01/18)
**NCM:** (latest as of 2018/01/18)
**OS:** Debian Stretch

## Minimal vimrc
```
" using vim-plug
call plug#begin('~/.local/share/nvim/plugged')
Plug 'roxma/nvim-completion-manager.git'
call plug#end()

set noshowmode
```

## Demo
![ncm-noshowmode](https://user-images.githubusercontent.com/35183444/35125454-8f041520-fca1-11e7-978e-1584cd134ba9.gif)

## Description
If you look at the bottom left of the above demo, you can see that unnecessary information is shown as the user types.

---

Regardless, thank you for the excellent plug-in.

**Comment by Shougo** [comment]
`set shortmess += c`

It is not nvim-completion-manager problem.

**Comment by bedax** [comment]
Ah okay, thanks for the reply.
