### ISSUE TITLE
the nvim-completion-manager not worked for third-party modules

### ISSUE THREAD

**Issue by duanmuq** [roxma/nvim-completion-manager#193]
I,m a newer for vim, I want to write python3 code in vim, so Ihave install this plug with neovim in ubuntu systerm. The jedi already installed using pip3 tools. In most case, this frame works good for python code.

The problem is some third-party modules using many .so files, I guess these are some function realized by c  or cpp code. and in this situation, the completion not worked. I have test the pygame and matplot mould, they both have the similar problem.  you can try this code:

import pygame
pygame.init()
screen = pygame.display.set_mode((640, 480), 0, 32)

The "set_mode" will not complete, and jedi-vim goto command also not work. The array fuction in numpy module have the same issue. I don't know how to solve this issue.

**Comment by Shougo** [comment]
I think it is jedi issue instead of nvim-completion-manager.
It should be reported in jedi issues.

**Comment by duanmuq** [comment]
thank you for your help, i will report this issue for jedi plug
