### ISSUE TITLE
insert 模式下pop menu太过灵敏。

### ISSUE THREAD

**Issue by pittcat** [roxma/nvim-completion-manager#194]
感觉在insert 模式下面用up down left right 移动的话，complete popup 感觉太灵敏了，up down 就会选择pop menu里面的东西了 ，insert下deoplete用<up><down> <left><right>移动的话好像没这么灵敏，比较自自然。调节cm_complete_popup_delay cm_complete_start_delay 的值可以解决，但是同时会出现补全不够快，不够灵敏。加了这个    
    inoremap <expr> <down> pumvisible() ? "\<C-e>" : "\<down>"
    inoremap <expr> <up>  pumvisible() ?  "\<C-e>" : "\<up>"
    inoremap <expr> <left> pumvisible() ? "\<C-e>" : "\<left>"
    inoremap <expr> <right> pumvisible() ? "\<C-e>" : "\<right>"
但是感觉这不是一个好的解决办法。
想要在insert 模式下，up down left right  移动的时候禁止popup

**Comment by likelxl** [comment]
顶一个，我也遇到过，关闭了自动触发补全
