### ISSUE TITLE
Parralle Process, communicating with main process

### ISSUE THREAD

**Issue by mhartington** [roxma/nvim-completion-manager#197]
Hi there!  Your PR to nvim-typescript has worked out very well so far.
But I was wondering if you had any way to work with the multi-process python API instead of vimscript API.

https://github.com/mhartington/nvim-typescript/blob/master/rplugin/python3/nvim_typescript/__init__.py#L699-L765

Since ncm runs the completion source as separate python process, the server would need to be recreated. But would it be possible to communicate back with the main process to send/receive data? I've been reading more into Python's Queue's but not 100% sure how they could fit into here. More of a question than an issue

**Comment by roxma** [comment]
I kinda want this feature too. But it's complicating things.

Bypass vim for plugin communication should have better performance. 

I'll not implement this feature in the short term. 

I'm closing this issue. Future discussion should be post at https://github.com/ncm2/ncm2/issues/4
