### ISSUE TITLE
python autocomplete error: E742: Cannot change value of v:completed_item.is_snippet = 0

### ISSUE THREAD

**Issue by fcying** [roxma/nvim-completion-manager#199]
vim 8.0 1-1475

when I select the python autocomplete popup menu, it make a error
![image](https://user-images.githubusercontent.com/106934/36658180-62fa6722-1b0a-11e8-8802-f2b5a83d72c0.png)
![image](https://user-images.githubusercontent.com/106934/36658192-6bfd8638-1b0a-11e8-8be3-8025e9adc630.png)

```
Error detected while processing function <SNR>24_check_changes[21]..cm#snippet#check_and_inject:
line    8:
E742: Cannot change value of v:completed_item.is_snippet = 0
```

my vimrc
```
set nocompatible
set guioptions=
set mouse=n

set runtimepath+=~/.vim/plugged/nvim-completion-manager
set runtimepath+=~/.vim/plugged/vim-hug-neovim-rpc

filetype plugin indent on
syntax enable
```

**Comment by Shougo** [comment]
Dup of https://github.com/roxma/nvim-completion-manager/issues/196.
