### ISSUE TITLE
[Question] Is there somewhere a list of sources defined?

### ISSUE THREAD

**Issue by andreyorst** [roxma/nvim-completion-manager#204]
Hello. I'm trying to figure out how to configure your plugin. It is bit tricky.

The thing that I can't understand is where I can check for source names, that `g:cm_sources_override` will understand.  For example, if I got it right, then this code:
```vim
let g:cm_sources_override = {
    \ 'cm-tags': {'enable':0}
    \ }
```
disables ctags completion source wich declared in [this list](https://github.com/roxma/nvim-completion-manager#completion-sources):
![image](https://user-images.githubusercontent.com/19470159/37480554-943a1f24-2890-11e8-9ce1-e57c24b4d8c5.png)

But it's not clear how would one find out, that _ctags source_ and `cm-tags` basically refer to one thing. I mean, if I didn't saw that `'cm-tags': {'enable':0}` I would never guessed that it will be named like so. And if someone would ask me to guess the name for the source, my first guess probably would be something like `ncm_ctags`, and if I would continue guessing I'll go for `cm_ctags` or `cm-ctags` but not the `cm-tags`. Maybe it's just me. I don't know. But back to the topic.

Is there a list of source names somewhere? I want to disable theese `~buf` `~cwd` and `~root` sources, because they're useless for me.
![image](https://user-images.githubusercontent.com/19470159/37457183-4c38040e-2852-11e8-989f-91afa08a67b1.png)
_`.sh` script, `kdeinit5__0` and `builder` (folder) are very useful completions, but I prefer not to see not C related completions, when I work with C code._

But I can't get how to define them in `g:cm_sources_override`. Or I'm missing something? I've looked through `NCM-settings` and `cm#register_source()` tags in `:help NCM` and read `:help ncm-source-examples` but that didn't clarify anything related to subject.

**Comment by Shougo** [comment]
You should specify `scopes` attribute in `cm-filepath` source.

If you want to complete filepath in .sh script only.

```vim
let g:cm_sources_override = {
    \ 'cm-filepath': {'scopes':['sh']}
    \ }
```

**Comment by andreyorst** [comment]
That's not quite what i'm asking for. IIUC you're provided a config that enables filepath completion only when editing .sh files, but i'm talking not about filepath is not a filepath. It's just filenames popup in C code.
Filepath completion usually is triggered when `/such/sequence/of/shashes/is/inserted/` and I would like to keep it when editing C, for sake of manual includes. But when I type variable name, I don't wan to see buffer name, and names contained in the folder where nvim was started. That's what is shown on the screenshot.

**Comment by Shougo** [comment]
OK.  I get it.

**Comment by andreyorst** [comment]
@DonnieWest I'll try it. Thanks.

**Comment by roxma** [comment]
This seems to be a sorting issue。 NCM forces the matches of higher priority source shows before the lower ones. But it's hard to find a perfect solutions

A list of possible solutions:
- use language support sources, they have the highest priority
- override source priorities
- create your own source that simply feeds the language keyword
- ncm2 could be configured to only popup the source with highest priority. https://github.com/ncm2/ncm2/issues/3

**Comment by andreyorst** [comment]
> This seems to be a sorting issue。

@roxma Actually, I don't think that this is sorting issue. The main issue here is that NCM is completing filenames, when it shouldn't do that. Like in sthe screenshoot at main comment to this issue:
![image](https://user-images.githubusercontent.com/19470159/42211723-e6e3da08-7ebc-11e8-84c2-164a40de4618.png)
There are certainly filenames in the list (which are not even opened in vim), yet i'm not in filepath completion mode.

I think that filenames should be completed when user have triggered filepath completion directly by typing `/\w`, `./` or `~/` (yet NCM toggles filepath completion with `//`).

Same thing with buffnames. I don't think that I ever need one in C file. Those may be shown with the lowest priority though.

**Comment by roxma** [comment]
In this case，try override the source’s cm_refresh_length，read the doc for more info
