### ISSUE TITLE
Overwriting priority for a built-in completer

### ISSUE THREAD

**Issue by ravicious** [roxma/nvim-completion-manager#212]
cm-filepath quite often populates the list with items I'm not interested in (since I rarely deal with file paths when writing in Ruby).

However, this completer is still useful for me in JS or when I just manually start a line with `/`.

Can I somehow overwrite its priority so its suggestions don't show up at the top of the list?

**Comment by Shougo** [comment]
```vim
let g:cm_sources_override = {
    \ 'cm-filepath': {'priority':1}
    \ }
```

**Comment by ravicious** [comment]
Thanks, I didn't thought it's that easy. >.<
