### ISSUE TITLE
get “nvim-completion-manager core channel terminated.” everytime i edit a file in terminal env.

### ISSUE THREAD

**Issue by lgy87** [roxma/nvim-completion-manager#213]
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5
zsh 5.4.2 (x86_64-apple-darwin17.3.0)
Python 3.6.4

---

<img width="607" alt="a" src="https://user-images.githubusercontent.com/17808424/38008946-436385b0-3284-11e8-854f-d089d133c2ce.png">

<img width="690" alt="b" src="https://user-images.githubusercontent.com/17808424/38008949-43a95a86-3284-11e8-995f-d33511fe53d7.png">

**Comment by Shougo** [comment]
You should upload more detailed executed command from neovim starting.

**Comment by lgy87** [comment]
@Shougo 
thank you for your reply.

sorry, i am a newbie here. but there is nothing special else i did.

1. `nvim` 
2. `:terminal`
3. `i` to entry **insert mode**
4. `nvim abc` to open a file

do you know where i can get the log of 'ncm', maybe it will help.

**Comment by Shougo** [comment]
I have tested, but I cannot reproduce the problem.

**Comment by lgy87** [comment]
yes, everything is ok without :terminal.

i will disable the plugins one by one, to make sure there isn't conflict between ncm and others.

**Comment by lgy87** [comment]
@Shougo 
Nope. I disabled all plugins but ncm.
the exception info is still there.


<img width="598" alt="c" src="https://user-images.githubusercontent.com/17808424/38011109-a0ee88e2-328e-11e8-9fbc-a267456c1726.png">

**Comment by Shougo** [comment]
> There's no guarantee that this plugin will be compatible with other completion plugin in the same buffer. Use let g:cm_smart_enable=0 and call cm#enable_for_buffer() to use this plugin for specific buffer.

I think you should enable ncm on specific buffer.

**Comment by lgy87** [comment]
@Shougo 
Yes, i changed `let g:cm_smart_enable=1` to `let g:cm_smart_enable=0`, the exception message has gone.

Thanks a lot. 👍
