### ISSUE TITLE
c key switches straight into insert mode

### ISSUE THREAD

**Issue by danprince** [roxma/nvim-completion-manager#214]
Seeing really strange behaviour using this plugin (at e724a442072261993ca503e969d2cb25722ab1d2) with Neovim v0.2.0 and the following vimrc.

```vim
if has('vim_starting')
  set nocompatible
  set runtimepath+=/Users/dan/Apps/repos/github.com/Shougo/dein.vim
endif

call dein#begin('/Users/dan/Apps/')
call dein#add('Shougo/dein.vim')
call dein#add('roxma/nvim-completion-manager')

call dein#end()

if dein#check_install()
  call dein#install()
endif
```

When I press <kbd>c</kbd> it switches straight into insert mode, rather than starting a change motion, like I would expect. The <kbd>d</kbd> key also has no effect. To make it stranger <kbd>v</kbd> still works fine.

So rather than <kbd>cw</kbd> changing the rest of the word under the cursor, it ends up just inserting a `w`.

It seems like `nvim-completion-manager` is hijacking the input step of some of the verbs.

Obviously this isn't the intended behaviour and this plugin used to work fine, but recently I reinstalled all my vim plugins and that was when this behaviour was introduced.

Any ideas what might be going wrong here and how I can fix it?

**Comment by danprince** [comment]
And just to confirm, I also get the same behaviour with vim-plug. Just to make sure Dein wasn't doing anything weird.

**Comment by Shougo** [comment]
> Seeing really strange behaviour using this plugin (at e724a44) with Neovim v0.2.0 and the following vimrc.

You should update neovim version.
neovim v 0.2.0 is too old.

**Comment by danprince** [comment]
Upgrading to v0.2.2 did the trick. Thanks!
