### ISSUE TITLE
very high CPU rate

### ISSUE THREAD

**Issue by yyscamper** [roxma/nvim-completion-manager#215]
I found the ncm occupy a very large CPU rate (70%-95%), the high CPU rate keeps for more than 30 minutes, and now it is still high.....

in vim windows, it stuck at `call jedi#goto_definitions`

![image](https://user-images.githubusercontent.com/511378/38234133-7f522066-374f-11e8-8b25-78b4569d2bef.png)

**Comment by morphheus** [comment]
NCM is its contents from various source. If you are using python, Jedi is one of those sources. In this case, it seems that Jedi itself is the problem, not NCM.

**Comment by zhengyhn** [comment]
Same issue for me when I save file. And It looks like memory leak also happened.

![image](https://user-images.githubusercontent.com/19358856/38767737-b22b3ea0-4019-11e8-9ba0-0be3c4cd8e66.png)

**Comment by roxma** [comment]
Discussion moves to https://github.com/ncm2/ncm2-jedi/issues/1
