### ISSUE TITLE
How to customize python path for jedi complemention?

### ISSUE THREAD

**Issue by ryanking8215** [roxma/nvim-completion-manager#220]
How to customize python path for jedi complemention?
It can be customized by `g:deoplete#sources#jedi#python_path` in deoplete.nvim like
```
   let g:deoplete#sources#jedi#python_path = /opt/python3.6/bin/python3.6
``` 
How to do that  with ncm? Thanks.

Btw, ncm is an awesome vim plugin.

**Comment by roxma** [comment]
Unfortunately this is impossible without setting the global g:python3_host_prog
