### ISSUE TITLE
Popup menu not displaying properly with long completion and two split windows

### ISSUE THREAD

**Issue by wangsongiam** [roxma/nvim-completion-manager#29]
This scenario comes with making a long completion in two panes.

![2017-02-26 21 12 31](https://cloud.githubusercontent.com/assets/19645990/23346496/affd9236-fc68-11e6-9a4c-521726b1d17b.gif)

**Comment by roxma** [comment]
I guess this is a neovim/gui  issue.

It sould be able to be reproduced with some plain `complete` call.

**Comment by roxma** [comment]
I'm posting an issue on neovim:
https://github.com/neovim/neovim/issues/6184

**Comment by wangsongiam** [comment]
thank you for explaining and making that issue!

**Comment by roxma** [comment]
This has been fixed on neovim upstream, closing this issue
