### ISSUE TITLE
add ability to manually trigger completion

### ISSUE THREAD

**Issue by prabirshrestha** [roxma/nvim-completion-manager#31]
Having something like `cm#manual_complete` would force refresh completions and show the autocomplete. Then anyone can add a mapping such as `<c-space>` to trigger it.

**Comment by roxma** [comment]
Disable auto popup and use `<c-g>` to trigger the popup:

```
g:cm_auto_popup = 0
imap <c-g> <Plug>(cm_force_refresh)
```

**Comment by muffinmad** [comment]
If you interested I'm created function to use tab to select the popup menu or trigger the popup:
```
function! SmartTab()
	if pumvisible()
		return "\<C-n>"
	endif
	let l:ctx = cm#context()
	let l:typed = l:ctx['typed']
	let l:kw = matchstr(l:typed,'\v\S+$')
	if len(l:kw)
		return cm#_force_refresh()
	endif
	return "\<Tab>"
endfunction

let g:cm_auto_popup = 0

imap <silent> <Tab> <c-r>=SmartTab()<cr>
```
