### ISSUE TITLE
Trigger popup with less than 3 characters?

### ISSUE THREAD

**Issue by adambiggs** [roxma/nvim-completion-manager#33]
I just moved over from deoplete, and so far this library seems like a big improvement!

Just wondering how I can trigger the completion popup with less the 3 characters. I couldn't find any setting for this in the docs.

**Comment by roxma** [comment]
Hi, I've just pushed an update for easier settings,

use `g:cm_refresh_default_min_word_len`  (`:help g:cm_refresh_default_min_word_len`)

If you want all sources to auto trigger popup with 2 characters:

use `let g:cm_refresh_default_min_word_len=2`

Current default is `[[1,4],[7,3]]` with the format `[ [ min priority, min length ], ... ]`

Which means sources with priority between 1 and 6 will have the value of 4, and sources with priority >= 7 will have the value of 3.
Priority >= 7 is more semantic completion source, So it's better to use a smaller value to trigger the popup than others.

If you want per value per source, read the documentation and use `g:cm_sources_override` instead (`:help g:cm_sources_override`)

By the way, There are users who tend to use longer word to trigger the popup to keep them from distraction. In this case, I would recommend `imap <somekey> <Plug>(cm_force_refresh)` to trigger patterns manually with short word.

**Comment by adambiggs** [comment]
Thanks for the quick response! The new option works great 🍻
