### ISSUE TITLE
Conflicts with Raimondi/delimitMate (neovim 0.1.7)

### ISSUE THREAD

**Issue by fantiq** [roxma/nvim-completion-manager#34]
with plug Raimondi/delimitMate  the option `delimitMate_expand_cr` is invalid.
the reason is the map `inoremap <CR>` is covered by plug  `roxma/nvim-completion-manager`

i found this in file `nvim-completion-manager/autoload/cm.vim` on line 61
```
 inoremap <expr> <buffer> <CR> (pumvisible() ? "\<c-y>\<cr>" : "\<CR>")
```

how to solve

**Comment by roxma** [comment]
@fantiq  
Hi, I've remove the mapping
