### ISSUE TITLE
TODO: integrate with ultisnips for completions with snippet

### ISSUE THREAD

**Issue by roxma** [roxma/nvim-completion-manager#36]
For example:

```
def foobar(param1,param2)
  pass

foobar|
```

`|` is the cursor position after `foobar` is completed by NCM, then press ultisnips expand trigger should expand the completion into
``` 
def foobar(param1,param2)
  pass

foobar(|<param1>,<param2>)
```

I'm not sure whether this is possible but it's worth a try

**Comment by roxma** [comment]
Ultisnips is kind of heavy and complicated for me.

So I started looking into [neosnippet](https://github.com/Shougo/neosnippet.vim) by @Shougo. It's more lightweight and easier to integrate, since it has been integrated in neocomplete already. Although I don't enjoy the display of '<`2:foo:`>'  placeholder. It's simple, and it works well.

Requirement:  installation of neosnippet and `let g:neosnippet#enable_completed_snippet=1`
Here's a screencast for python completion and expansion:

A `+` sign means the completion item is expandable.

![soutput](https://cloud.githubusercontent.com/assets/4538941/23655114/b4693a66-036e-11e7-824f-ac822547fdec.gif)


This feature is still experimental. 

Besides, the syntax of  [neosnippet](https://github.com/Shougo/neosnippet.vim) by @Shougo and  [snipmate](https://github.com/garbas/vim-snipmate) maintained by @garbas seems to be compatible at some level.

I'll look into snipmate as another alternative when I have some free time available.

**Comment by roxma** [comment]
Closing this, snipmate support may be implemented in the future. But this is not high priority.

**Comment by roxma** [comment]
[snipmate](https://github.com/garbas/vim-snipmate) is supported now

![output](https://cloud.githubusercontent.com/assets/4538941/23830375/4ce84844-0744-11e7-8220-529f990ba189.gif)


// cc @ajzafar @garbas

**Comment by Battleroid** [comment]
Does anything special need to be done in order to get snippets provided by Ultisnips to expand?

**Comment by roxma** [comment]
@Battleroid

No. This issue is about parameter expansion.

**Comment by roxma** [comment]
@battleroid
I’m not sure what you need. But this might be useful.
https://github.com/roxma/nvim-completion-manager/issues/89

**Comment by Battleroid** [comment]
Thank you, I'll poke at it.
