### ISSUE TITLE
Issues about file path and c++ header completion and neosnippet

### ISSUE THREAD

**Issue by theFool32** [roxma/nvim-completion-manager#37]
nvim @ Arch

File path completion with nvim-completion-manager is not complete:
![image](https://cloud.githubusercontent.com/assets/3063690/23577335/5127bf28-00f7-11e7-86fb-ced6df6e2b4a.png)
While use c-x c-f,  all files are listed.
![image](https://cloud.githubusercontent.com/assets/3063690/23577339/60756034-00f7-11e7-95e7-6475abe13b26.png)

---

I install  clang_complete for c++ completion and notice it can't complete header.  [here](https://github.com/Rip-Rip/clang_complete/issues/466)  gives a plugin which is not compatible with.  Any suggestion?

---

By the way, I want to know whether there exists a plan to support [neosnippet](https://github.com/Shougo/neosnippet.vim/) since I recognize it as more convenient to use when compared with Ultisnips.

---

Thanks for the nice plugin.

**Comment by roxma** [comment]
How many files are there in your /usr/lib directory? current file completion source limits the matches to 1024 files before filtering

**Comment by roxma** [comment]
I've pushed an update which may fix the filepath issue.

For neosnippet, [this](https://github.com/prabirshrestha/asyncomplete-neosnippet.vim) by @prabirshrestha  looks like a nice implementation, I'll try find some time and port it to NCM and test it. 

PRs are welcomed. If you have time, it should be simple like how it's done in the [ultisnips source](https://github.com/roxma/nvim-completion-manager/blob/master/autoload/cm/sources/ultisnips.vim).

C/C++ Include path completion is in my todo list, too.

**Comment by roxma** [comment]
@prabirshrestha 
How about we setup an agreement on how pure vimscript handlers share the same style, so that both asyncomplete and NCM will benifits from it without much effort?

For example, 
```
call asyncomplete#complete(a:opt['name'], a:ctx, l:startcol, l:matches)
```

becomes

```
call call(a:ctx['callback'],[a:opt['name'], a:ctx, l:startcol, l:matches])
```

**Comment by roxma** [comment]
Sorry, closed by accident

**Comment by theFool32** [comment]
File path completion works. Thanks.

**Comment by roxma** [comment]
@theFool32 
neosnippets added. It feels lighter than ultisnips. 

Since it's popular, and the overhead added for this source is small, I'm making it builtin source for convenience.

**Comment by theFool32** [comment]
Oh god. You'r so effective!!!

**Comment by roxma** [comment]
Close this issue.

Open https://github.com/roxma/clang_complete/issues/4 for header completion.
