### ISSUE TITLE
Ultisnips stopped working in visual mode

### ISSUE THREAD

**Issue by rafaeln** [roxma/nvim-completion-manager#38]
I have the following LaTeX snipped:

```snippets
snippet it "Italics" i
\\textit{${1:${VISUAL}}}${0}
endsnippet
```

Which allows me to visually select some text I want to italicize, say, the word `text`, press `<tab>`, which makes the text `text` disappear and puts me in insert mode, type `it` and press `<tab>` again, which then gives me `\textit{text}`. Somehow, if I'm using `nvim-completion-manager`, that stops working.

**Comment by roxma** [comment]
I guess this is due to the `<Tab>` mapping recommended by NCM conflicts your ultisnips mapping? If you remove this mapping from your vimrc, it should work.
 
```vim
inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
```

**Comment by roxma** [comment]
It's kind of tricky to integrated these mappings. Currently I'm using `<c-j>` as next (normal j is down key, easier to remember for me) and `<c-k>` as prev for jumping around snippet field, instead of `<Tab>`, to avoid mapping conflicts.

**Comment by roxma** [comment]
Just read Ultisnips documentation, here's what I've tried  to integrate the mappings without conflict:

```
vnoremap <expr> <Plug>(snips_result_check) g:ulti_expand_or_jump_res?'':"\<Tab>"
inoremap <expr> <Plug>(snips_result_check) g:ulti_expand_or_jump_res?'':"\<Tab>"
imap <expr> <Tab> (pumvisible() ? "\<C-n>" : "\<C-r>=UltiSnips#ExpandSnippetOrJump()\<cr>\<Plug>(snips_result_check)")
```

**Comment by roxma** [comment]
Just tweaked a complete version, this works on my neovim:

```vim
    let g:UltiSnipsExpandTrigger        = "<Plug>(ultisnips_expand)"
    let g:UltiSnipsJumpForwardTrigger   = "<Plug>(ultisnips_expand)"
    let g:UltiSnipsJumpBackwardTrigger  = "<Plug>(ultisnips_backward)"
    let g:UltiSnipsListSnippets         = "<Plug>(ultisnips_list)"
    let g:UltiSnipsRemoveSelectModeMappings = 0 
    vnoremap <expr> <Plug>(ultisnip_expand_or_jump_result) g:ulti_expand_or_jump_res?'':"\<Tab>"
    inoremap <expr> <Plug>(ultisnip_expand_or_jump_result) g:ulti_expand_or_jump_res?'':"\<Tab>"
    imap <expr> <Tab> (pumvisible() ? "\<C-n>" : "\<C-r>=UltiSnips#ExpandSnippetOrJump()\<cr>\<Plug>(ultisnip_expand_or_jump_result)")
    xmap <Tab> <Plug>(ultisnips_expand)
    smap <Tab> <Plug>(ultisnips_expand)
    autocmd! User UltiSnipsEnterFirstSnippet xmap <Tab> <Plug>(ultisnips_expand)
    autocmd! User UltiSnipsEnterFirstSnippet smap <Tab> <Plug>(ultisnips_expand)

    vnoremap <expr> <Plug>(ultisnips_backwards_result) g:ulti_jump_backwards_res?'':"\<S-Tab>"
    inoremap <expr> <Plug>(ultisnips_backwards_result) g:ulti_jump_backwards_res?'':"\<S-Tab>"
    imap <expr> <S-Tab> (pumvisible() ? "\<C-p>" : "\<C-r>=UltiSnips#JumpBackwards()\<cr>\<Plug>(ultisnips_backwards_result)")
    xmap <S-Tab> <Plug>(ultisnips_backward)
    smap <S-Tab> <Plug>(ultisnips_backward)

```

**Comment by roxma** [comment]
Remove the `<Tab>` mapping provided by NCM, and the trigger keys configuration for ultisnips,

This version should work better for both plugins.

And if there's an openning popup menu get in the way, use `<c-y>` to close the popup menu. Or simple map another key, `<c-u>` in this example, to trigger ultisnips.

```vim
    let g:UltiSnipsExpandTrigger        = "<Plug>(ultisnips_expand)"
    let g:UltiSnipsJumpForwardTrigger   = "<Plug>(ultisnips_expand)"
    let g:UltiSnipsJumpBackwardTrigger  = "<Plug>(ultisnips_backward)"
    let g:UltiSnipsListSnippets         = "<Plug>(ultisnips_list)"
    let g:UltiSnipsRemoveSelectModeMappings = 0 

    vnoremap <expr> <Plug>(ultisnip_expand_or_jump_result) g:ulti_expand_or_jump_res?'':"\<Tab>"
    inoremap <expr> <Plug>(ultisnip_expand_or_jump_result) g:ulti_expand_or_jump_res?'':"\<Tab>"
    imap <silent> <expr> <Tab> (pumvisible() ? "\<C-n>" : "\<C-r>=UltiSnips#ExpandSnippetOrJump()\<cr>\<Plug>(ultisnip_expand_or_jump_result)")
    xmap <Tab> <Plug>(ultisnips_expand)
    smap <Tab> <Plug>(ultisnips_expand)

    vnoremap <expr> <Plug>(ultisnips_backwards_result) g:ulti_jump_backwards_res?'':"\<S-Tab>"
    inoremap <expr> <Plug>(ultisnips_backwards_result) g:ulti_jump_backwards_res?'':"\<S-Tab>"
    imap <silent> <expr> <S-Tab> (pumvisible() ? "\<C-p>" : "\<C-r>=UltiSnips#JumpBackwards()\<cr>\<Plug>(ultisnips_backwards_result)")
    xmap <S-Tab> <Plug>(ultisnips_backward)
    smap <S-Tab> <Plug>(ultisnips_backward)

    " optional
    inoremap <silent> <c-u> <c-r>=cm#sources#ultisnips#trigger_or_popup("\<Plug>(ultisnips_expand)")<cr>
```

**Comment by roxma** [comment]
neosnippet version:

```vim
    imap <expr> <Tab> neosnippet#mappings#expand_or_jump_impl()
    imap <expr> <Tab> (pumvisible() ? "\<C-n>" : (neosnippet#mappings#expand_or_jump_impl()!=''?neosnippet#mappings#expand_or_jump_impl():"\<Tab>"))
    smap <Tab>     <Plug>(neosnippet_expand_or_jump)  
    xmap <Tab>     <Plug>(neosnippet_expand_target)   
    " neosnippet doesn't have jump back key
    imap <expr> <S-Tab> (pumvisible() ? "\<C-p>" : "\<S-Tab>")
```

@Shougo  I found this is also useful for deoplete.nvim with ultisnips or neosnippet

**Comment by Shougo** [comment]
> @Shougo I found this is also useful for deoplete.nvim with ultisnips or neosnippet

It is already explained in neosnippet examples.

**Comment by rafaeln** [comment]
Now this works perfectly for me! Thanks!

**Comment by partounian** [comment]
I just moved all of my config from deoplete and more to NCM and neosnippet. 

It was pretty smooth but I can't figure out how to expand snippets. (I am using the code you have shown above). At this moment tab also goes through the list of autocomplete suggestions. Also, I seem to be getting snippets as part of the menu, but autocompletion of words in the buffer only at times.

**Comment by roxma** [comment]
@partounian 

Could you provide detailed description of how to reproduce the problem and your minimal vimrc?

**Comment by partounian** [comment]
@roxma 

Well before I break up my vim, I have a question about this snippet.

```
    imap <expr> <Tab> (pumvisible() ? "\<C-n>" : (neosnippet#mappings#expand_or_jump_impl()!=''?neosnippet#mappings#expand_or_jump_impl():"\<Tab>"))
    smap <Tab>     <Plug>(neosnippet_expand_or_jump)  
    xmap <Tab>     <Plug>(neosnippet_expand_target)   
    " neosnippet doesn't have jump back key
    imap <expr> <S-Tab> (pumvisible() ? "\<C-p>" : "\<S-Tab>")
```

It seems that Tab is what is used to expand a Snippet? I am confused on how it is supposed to expand when it only goes through the list of autocomplete options.

**Comment by roxma** [comment]
```
imap <expr> <Tab> (pumvisible() ? "\<C-n>" : (neosnippet#mappings#expand_or_jump_impl()!=''?neosnippet#mappings#expand_or_jump_impl():"\<Tab>"))
```

This mappings use `<tab>` to move over the completion items when popup menu is visible.

If you want to expand a snippet, you need to close the popup menu first, with a `<c-y>` key for example.

This mapping is just a trick but I personally don't use this mapping, it is not as convenient as it seems. I prefer to use a separate key for expanding snippet, and going through placeholders.
