### ISSUE TITLE
<c-x><c-n>-like completion not working in vim

### ISSUE THREAD

**Issue by rafaeln** [roxma/nvim-completion-manager#39]
That's just it. Even though `nvim-completion-manager` does work on vim (with `vim-hug-neovim-rpc`), the <c-x><c-n>-like completion source doesn't get activated, neither by `<Plug>(cm_force_refresh)` nor after the third repeated word in a row.

**Comment by roxma** [comment]
Have you updated `vim-hug-neovim-rpc` to the latest version? 

This feature requires the new version updated [a day ago](https://github.com/roxma/vim-hug-neovim-rpc/commit/2b6fd377a436c0f75442e034a3f823782d71d18a)

**Comment by rafaeln** [comment]
Oops, sorry. Should have updated before filing the issue. It does work with the latest commit
