### ISSUE TITLE
Working in virtualenv

### ISSUE THREAD

**Issue by imbolc** [roxma/nvim-completion-manager#42]
Thanks, I really like NCM. But when I'm working in virtualenv NCM works only if neovim installed in this virtualenv. Deoplete bypasses this problem somehow.

**Comment by roxma** [comment]
Maybe you need this plugin, it automatically setup virtualenv for you ,

https://github.com/roxma/python-support.nvim

**Comment by roxma** [comment]
In case you don't want a plugin for this, you should read this wiki: https://github.com/zchee/deoplete-jedi/wiki/Setting-up-Python-for-Neovim

**Comment by roxma** [comment]
I'm closing this, since this is neither a but or a feature request. I'll reopen it if things turns otherewise.
