### ISSUE TITLE
Python completion: Unnecessary `=` character completion for argument variable

### ISSUE THREAD

**Issue by theFool32** [roxma/nvim-completion-manager#43]
![image](https://cloud.githubusercontent.com/assets/3063690/23587440/ee97f9d6-01e6-11e7-982b-4f6e2bba8b46.png)

Just like the image above shows,   it should be `testParam` instead of `testParam=`.

**Comment by roxma** [comment]
This is how the jedi library behave, I'm posting an issue to jedi_vim: https://github.com/davidhalter/jedi-vim/issues/691
