### ISSUE TITLE
<Plug>(cm_force_refresh) not working properly on Vim8 on Windows

### ISSUE THREAD

**Issue by xtal8** [roxma/nvim-completion-manager#47]
I'm using NCM on Windows with Vim8. I disabled automatic completions with `let g:cm_auto_popup = 0` and I use `<Plug>(cm_force_refresh)` to initiate completions manually. However, completions don't appear when I use `<Plug>(cm_force_refresh)` first time, I have to press it two times for completions to appear.

**Comment by roxma** [comment]
I can't reproduce it.

Could you reproduce this with 

```
set NVIM_PYTHON_LOG_FILE=nvim.log
set NVIM_NCM_LOG_LEVEL=DEBUG
nvim test.js
```

and show the contents of the `nvim.log_py3_cm_core` and `nvim.log_py3_cm_sources.cm_tern`?

**Comment by roxma** [comment]
There's a possible cause of this issue, the `<Plug>(cm_force_refresh)` is triggered before the source channel started.

On my machine, all channels start within 3 seconds. It's hard to reproduce it in this case.

So I guess there may be other causes, which is why the log files are needed.

**Comment by xtal8** [comment]
I tried it with minimal vimrc and couldn't reproduce the issue. Then I tried removing chunks of my vimrc and found out that
```
set guicursor=a:blinkon0          " disable blinking
```
is to blame. When I have it set I need to press `<Plug>(cm_force_refresh)` two times, without it it works as intended, even though it has small delay.


This is my minimal vimrc
```
call plug#begin()

Plug 'roxma/nvim-completion-manager'
if !has('nvim')
    Plug 'roxma/vim-hug-neovim-rpc'
endif
Plug 'roxma/nvim-cm-tern',  {'do': 'npm install'}

let g:cm_auto_popup = 0
imap <tab> <Plug>(cm_force_refresh)
set guicursor=a:blinkon0          " disable blinking

call plug#end()
```

Steps to reproduce:
1. open blank buffer
2. type fooooobaaaar
3. type foooo
3. type <tab>

I have to press tab 2 times to get completions. It only happens in gvim.


nvim.log_py3_cm_core:
http://pastebin.com/Mb8fzSdz
nvim.log_py3_cm_sources.cm_tern:
http://pastebin.com/kBetxuTc

**Comment by roxma** [comment]
Thanks! I'll look into that.

**Comment by roxma** [comment]
It seems there's something wrong with vim's timer according to the log files, I switch to python implementation for the timer.

Update both plugin, NCM and nvim-cm-tern, and check whether the issue is still happening.

If it's still happening, I'll still need the log files.

**Comment by xtal8** [comment]
It's happening in a buffer without ft set also. Issue is not exclusively related to tern source. I updated plugins and it's still happening. 
Log file:
http://pastebin.com/J57apttu

**Comment by roxma** [comment]
I get this reproduced. 

The popup menu is displayed after seconds, or 10+ seconds. But according to the log file, the complete process is finished in 1 seond. I believe this is a vim issue.

 I also noticed that if I press <ctrl> after I press `<Plug>(cm_force_refresh)`, the menu will be displayed.

**Comment by roxma** [comment]
Oh I got a workaround, just put this into your vimrc:

```vim
func g:Foo(...)
" do nothing
endfunc
call timer_start(100,function('g:Foo'),{'repeat':-1})
```

I guess this somehow activates vim's timer, and then the screen gets updated.

**Comment by roxma** [comment]
This may also be related to the ncm-tern slow issue you reported on https://github.com/roxma/nvim-cm-tern/issues/2

**Comment by xtal8** [comment]
The workaround solves my issue. 

As for tern issue, completions are still slow. I get buffer completions instantly and then after a second or two tern completions. I get the same delay with both automatic and manual completion.

**Comment by xtal8** [comment]
I encountered similar issue in ALE and Neomake and I would like to report issue directly to Vim. But I struggle with producing minimal reproducible case. Is this issue connected with job_start function?

**Comment by roxma** [comment]
This issue is related to timer and vim's rpc somehow.

If there's no timer started, the display of popup menu get significantly delayed.
