### ISSUE TITLE
New line issue

### ISSUE THREAD

**Issue by neilpeter08** [roxma/nvim-completion-manager#49]
When i wanted to add a newline i have to press enter twice, first is to exit the suggestion window, the next one is to enter a new line, how do i prevent this from happening?

**Comment by roxma** [comment]
Use a mapping

```vim
inoremap <expr> <buffer> <CR> (pumvisible() ? "\<c-y>\<cr>" : "\<CR>")
```

**Comment by roxma** [comment]
```vim
inoremap <expr> <CR> (pumvisible() ? "\<c-y>\<cr>" : "\<CR>")
```

`<buffer>` should be removed here. Sorry on the wrong mapping.

**Comment by neilpeter08** [comment]
Thanks @roxma! But it looks like this mapping has a conflict with vim-endwise. Just wanted to let you know :)

**Comment by neilpeter08** [comment]
I've removed endwise because its not needed with this completion manager anymore

**Comment by roxma** [comment]
I haven't tried endwise, it seems this is the mapping used by endwise internally

```vim
    imap <CR> <CR><Plug>DiscretionaryEnd
    imap <script> <C-X><CR> <CR><SID>AlwaysEnd
```

Chain the two mappings together

```vim
let g:endwise_no_mappings = 1
imap <script> <C-X><CR> <CR><SID>AlwaysEnd
imap <expr> <CR> (pumvisible() ? "\<C-Y>\<CR>\<Plug>DiscretionaryEnd" : "\<CR>\<Plug>DiscretionaryEnd")
```

**Comment by neilpeter08** [comment]
what a god

**Comment by sassanh** [comment]
@roxma what's `<c-y>`? the above mapping just goes to new line for me.

**Comment by roxma** [comment]
@sassanh 

`:help ins-completion`

>CTRL-Y  Yes: Accept the currently selected match and stop completion.

It has different meaning when the completion menu is not visible. `:help i_CTRL-Y`

**Comment by sassanh** [comment]
Yeah, I searched for `i_CTRL-Y`. But why do you have a `<cr>` after it, it just makes a newline for me. Another issue is it doesn't expand snippets. Is `<c-y>` (accepting the currently selected match) supposed to expand snippets? What I want is to accept completions or expand snippets both with a single key.

**Comment by roxma** [comment]
> But why do you have a &lt;cr&gt; after it.

This is what I get used to. And I add this to the README to remind the `When i wanted to add a newline i have to press enter twice` issue.

> Another issue is it doesn't expand snippets. 

You need to feed the snippet expand key then. I think it is possible to tweak the mapping to do so, after spanding a while reading the snippet engine documentation.

> Is &lt;c-y&gt; (accepting the currently selected match) supposed to expand snippets?

I'm not sure. It depends on what you would like to.

**Comment by roxma** [comment]
@sassanh 

> What I want is to accept completions or expand snippets both with a single key.

If you're using `ctrl-n` `ctrl-p`  instead of `up` and `down` to move around the menu, you've already accepted the completion item. All you need is the snippet expand key after selection.

**Comment by sassanh** [comment]
@roxma 
Thanks for info.
I'm using `<tab>` `<c-tab>`, I'm using UltiSnips, and need something like
```
imap <cr> pumvisible() ? selectedItemIsSnippet() ? "\<C-R>=UltiSnips#ExpandSnippet()\<CR>" : "\<C-Y>" : "\<CR>"
```
(it doesn't work) so that whenever I hit `<cr>` it either accept the completion or expand the snippet based on whether a snippet is selected or it's just a normal auto completion.
Is there anyway I can simulate `selectedItemIsSnippet()` in ncm?

**Comment by roxma** [comment]
@sassanh 

It's impossible with current version of ncm.

The snippet is checked and registered to the snippet engine  dynamicly, every 30ms (hacky, I know). So `selectedItemIsSnippet()` won't work.

Maybe it needs another api to check if the `v:completed_item` has snippet. This way, it could be checked and registered by a key. After that, it could be expanded.

**Comment by sassanh** [comment]
I see, I'll make a PR for it if I get obsessed enough 😄

**Comment by roxma** [comment]
@sassanh 

I‘ve edited the response. It's possible in some situation. In case you missied it.
