### ISSUE TITLE
Support for deoplete plugins

### ISSUE THREAD

**Issue by JelteF** [roxma/nvim-completion-manager#50]
There's a lot of deoplete plugins that exist. Would it be possible to add support for those in this library? Or maybe just to have full deoplete as one of the sources.

**Comment by roxma** [comment]
It's easier to have full deoplete as one of the sources. But I don't want to maintain this feature. So Here's the code:

```vim
" force init deoplete then hack deoplete's mapping
call deoplete#enable()

" register as ncm source
au User CmSetup call cm#register_source({'name' : 'deoplete',
        \ 'priority': 7,  
        \ 'abbreviation': '', 
        \ })

" hack deoplete's mapping
inoremap <silent> <Plug>_ <C-r>=g:Deoplete_ncm()<CR>

func! g:Deoplete_ncm()
  " forward to ncm
  call cm#complete('deoplete', cm#context(), g:deoplete#_context.complete_position + 1, g:deoplete#_context.candidates)
  return ''
endfunc

```

It is possible to support deoplete's python source. But that might take a lot of work. So I have no plan for this currently.

**Comment by charliesbox** [comment]
@roxma so, by using this snippet, is not necessary to have installed deoplete too?

I wanna start using this plugin as my only autocomplete manager, but `elm` autocompletion sources just have support for deoplete and YCM

**Comment by roxma** [comment]
@charliesbox 

The snippet needs deoplete.

Looks like [elm-vim](https://github.com/ElmCast/elm-vim) has omni function. You could use simillar config as it is for css. Note that omni completion is running on the same thread as nvim's main thread, though. I'd rather create a plugin for ncm if I have the time.

```vim
" css completion via `csscomplete#CompleteCSS`
" The `'cm_refresh_patterns'` is PCRE.
" Be careful with `'scoping': 1` here, not all sources, especially omnifunc,
" can handle this feature properly.
au User CmSetup call cm#register_source({'name' : 'cm-css',
		\ 'priority': 9, 
		\ 'scoping': 1,
		\ 'scopes': ['css','scss'],
		\ 'abbreviation': 'css',
		\ 'cm_refresh_patterns':[':\s+\w*$'],
		\ 'cm_refresh': {'omnifunc': 'csscomplete#CompleteCSS'},
		\ })
```

**Comment by roxma** [comment]
@charliesbox 

Please test this fork: https://github.com/roxma/elm-vim

I think it's working for me, though, I'm not familiar with elm.

I'll open a pr after you confirm it's working.

**Comment by charliesbox** [comment]
@roxma is not working for me :( 

did you added an extra config along with the plugin? 

When I press, for example, `String.`, I don't receive a completion of the functions

**Comment by davidosomething** [comment]
Something to note when forwarding completions from deoplete as above, you should disable the following:

```
let g:deoplete#ignore_sources._ = {}
let g:deoplete#ignore_sources._ = [
      \   'buffer',
      \   'member',
      \   'tag',
      \   'file',
      \   'around',
       \ ]
```

This is because NCM already implements those completions (at relatively the same speed too).
