### ISSUE TITLE
Ruby Rcodetools integration

### ISSUE THREAD

**Issue by sphynx79** [roxma/nvim-completion-manager#54]
Please can you help me to use your plugin with rcodetools.

In this moment i use https://github.com/lifepillar/vim-mucomplete and work.

set completefunc give me this <SNR>21_RCT_completion

can i use this completefunc??

**Comment by roxma** [comment]
Doesn't support rcodetools's  `completefunc`

1. Don't use vim's builtin `complete_add` function. If you are using NCM, popup menu should always be managed by NCM.  Simply return all the matches as array.
2. Also avoid `complete_check`
3. `s:RCT_completion` should be defined as global function. It's hard to get the real script function name outside the script.
4. even avoid `omnifunc` if it's possible.

**Comment by roxma** [comment]
Just looked into rcodetools's completefunc, it's not hard to convert it into ncm source

Here's the demo code, simply place it into ncm's installation directory as `pythonx/cm_sources/rcodetools.py`. 

```python
# -*- coding: utf-8 -*-

from cm import register_source, getLogger, Base

register_source(name='rcodetools',
                priority=9,
                abbreviation='rb',
                scoping=True,
                scopes=['ruby'],
                sort=0,
                cm_refresh_patterns=[r'\.$'],)

import subprocess

logger = getLogger(__name__)

class Source(Base):

    def __init__(self,nvim):
        super(Source,self).__init__(nvim)

    def cm_refresh(self,info,ctx,*args):

        src = self.get_src(ctx)

        # use stdin for rct-complete
        proc = subprocess.Popen(args=['rct-complete',
            '--completion-class-info',
            '--dev',
            '--fork',
            '--line=%s' % ctx['lnum'],
            '--column=%s' % (ctx['col']-1),
            '--filename=%s' % ctx['filepath']
            ],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL)

        result, errs = proc.communicate(src.encode('utf-8'),timeout=30)
        logger.debug("result %s", result)

        result = result.decode('utf-8')
        logger.info("result %s", result)

        results = result.split("\n")
        if not results:
            return

        matches = []
        for line in results:

            # sayHi\tHelloWorld#sayHi
            fields = line.split("\t")
            if not fields:
                continue

            word = fields[0]
            menu = ''
            if len(fields)>1:
                menu = fields[1]

            if not word.strip():
                continue

            item = dict(word=word,
                        icase=1,
                        dup=1,
                        menu=menu,
                        )

            matches.append(item)

        logger.info('matches %s', matches)
        self.complete(info, ctx, ctx['startcol'], matches)

```

You could use this as a start, and maintain a git repo for this purpose.

I didn't put it into NCM's repo or create another repo because I just learned how to write ruby's hello-world, I'm not capable of maintaining this.

Here's the screencast:

![output](https://cloud.githubusercontent.com/assets/4538941/23935939/10a1a194-098a-11e7-8ff5-6c8fe80565c7.gif)

**Comment by sphynx79** [comment]
I'm sorry but this not work for me, i put your script in nvim\plugged\nvim-completion-manager\pythonx\cm_sources\cm_rcodetools.py and restart nvim.
But not work, maybe beacause i use windows, and a i saw in your script that you use fork in subprocess.Popen, but windows not support fork.

I resolve this problem with https://github.com/osyo-manga/vim-monster, i install this plugin and put in my init.vim

au User CmSetup call cm#register_source({'name' : 'monster',
			\ 'priority': 9, 
			\ 'scoping': 1,
			\ 'scopes': ['ruby'],
			\ 'abbreviation': 'rb',
			\ 'cm_refresh_patterns':['[^. *\t]\.\w*', '[a-zA-Z_]\w*::'],
			\ 'cm_refresh': {'omnifunc': 'monster#omnifunc'},
			\ })



![2017-03-15_11-24-18](https://cloud.githubusercontent.com/assets/5004160/23944366/e7720b4a-0972-11e7-9d17-f291c4ca62db.gif)

**Comment by roxma** [comment]
Make sure `rct-complete` command is availabe on your windows.

You need to install rcodetools then setup PATH environment variable.

Popen is available on windows, if you are on windows, you need to change 

```python
        proc = subprocess.Popen(args=['rct-complete',
```

into 

```python
        proc = subprocess.Popen(args=['ruby', 'path/to/rct-complete`
```

**Comment by roxma** [comment]
If it is still not working, follow the instructions from the [README#trouble-shooting](https://github.com/roxma/nvim-completion-manager#trouble-shooting) section for debugging.
