### ISSUE TITLE
Support goto definition

### ISSUE THREAD

**Issue by kepbod** [roxma/nvim-completion-manager#56]
NCM has integrated with jedi and it works great, but I am wondering if it could also support goto definition.

**Comment by fantiq** [comment]
phper hope too

**Comment by roxma** [comment]
Planning on that.

Currently I’m using jedi-vim for jumping.

**Comment by Shougo** [comment]
I think you should use LangServer for it.
https://github.com/autozimu/LanguageClient-neovim

**Comment by prabirshrestha** [comment]
Even I think this is out of scope and should be provided by other plugins like LSP.

**Comment by roxma** [comment]
It would violates the 'do one thing and do it well' principle for NCM to support too much features. 

Somehow I still miss easier setup with minimal plugins and go-to-declarations and so on. If  I'm doing this I may end up with adding more features and more bugs and more work to do. I haven't figured out a better solution.

I agree that LSP  is always  a good solution.

**Comment by sassanh** [comment]
I also think ncm shouldn't support it. There's no significant benefit for having few plugins. It's better to have plugins that each does its own job. If some day I want to use a fork of `jedi-vim` I can do it easier if it's a stand alone plugin.

**Comment by roxma** [comment]
Closing. After a while I think this feature is not necessary. And even if it is, it should be done with another plugin, instead of pushing the complexity into ncm.
