### ISSUE TITLE
File path completion is not triggered

### ISSUE THREAD

**Issue by FuzzOli87** [roxma/nvim-completion-manager#57]
On a javascript file(haven't tried it on any other type of file) filepath completion does not trigger.

I have nvim-cm-tern, Languageclient-neovim installed and all the python modules mentioned in the README.
![filepath](https://cloud.githubusercontent.com/assets/12246915/24020590/cd60bce4-0a6a-11e7-91c5-d7766f0c18c0.gif)

**Comment by roxma** [comment]
Just pushed an update, try the newest version.

**Comment by FuzzOli87** [comment]
Tried the new update and it works like a charm! Thanks!
