### ISSUE TITLE
<SNR>#_on_core_channel_exit upon exiting neovim

### ISSUE THREAD

**Issue by megalithic** [roxma/nvim-completion-manager#6]
Hey there @roxma, loving this plug, super fast and works well so far. Just have one minor issue, with this plugin installed and enabled via vim-plug, i get the following output when exiting neovim:

```sh
E118: Too many arguments for function: 5
E118: Too many arguments for function: <SNR>76_on_core_channel_exit
E118: Too many arguments for function: 6
```

Please let me know if there are any steps you'd like me to do for debugging or any additional info you'd need.

I'm on OS X 10.11.6, iterm2 nightly, neovim-HEAD.

Thanks!

**Comment by megalithic** [comment]
@roxma as a quick update, upon entering a `js` file, i get the following message in neovim's command input: `E118: Too many arguments for function: 24`.

Also, I'm getting regular segfaults with not touching anything with a file/buffer opened with the following:

`nvim(93754,0x700000801000) malloc: *** error for object 0x7fe8dbc25a18: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug`

**Comment by megalithic** [comment]
I've got jedi, and tern_for_vim installed as well.

**Comment by roxma** [comment]
```E118: Too many arguments for function: <SNR>76_on_core_channel_exit``` Should be fixed now.

I'm using neovim 1.7, It seems you're using an unstable version, `neovim-HEAD`, this is possibly related to the malloc issue.

**Comment by megalithic** [comment]
@roxma i'll flip back to stable on neovim and see if the malloc issues resolve. thanks much!!

**Comment by megalithic** [comment]
@roxma last little item from that fix for this issue.. upon exit, now seeing: `W19: Deleting augroup that is still in use`. i know this is a minor item, just want to help you get this thing super stable!

**Comment by megalithic** [comment]
will also post back about moving to neovim stable.

**Comment by megalithic** [comment]
@roxma no crash yet on 1.7; will stick to that for a while.

also, still, i'm wondering how you're getting `javascript` completion; i have tern_for_vim installed with the proper npm package installed. e.g., what i had working for deoplete/deoplete-ternjs.

i'd love to get that awesome JS completion like you have in your asciicinema!

thanks again :D
