### ISSUE TITLE
[Question] Do I Still Need YCM

### ISSUE THREAD

**Issue by jrock2004** [roxma/nvim-completion-manager#61]
Does this plugin replace YouCompleteMe or should I still use it?

**Comment by roxma** [comment]
I'm not sure, YCM has more completion sources and features. It seems YCM has go-to-declaration, which NCM doesn't have. But I haven't used YCM for a long time, so I can't provide detailed comparison.

For me, I'm intended to make NCM better in order to replace YCM in most cases.

**Comment by jrock2004** [comment]
Ok, so that means I need to use one or the other and not both. Thanks

**Comment by roxma** [comment]
I get what you mean now.

This is also explained in the README page.

> There's no guarantee that this plugin will be compatible with other completion plugin in the same buffer. Use let g:cm_smart_enable=0 and call cm#enable_for_buffer() to use this plugin for specific buffer.
