### ISSUE TITLE
Does anyone have came across memory leak?

### ISSUE THREAD

**Issue by theFool32** [roxma/nvim-completion-manager#62]
It happens 3 times recently when editing python script.
I don't know how to reproduce it.

OS: Arch Linux
Kernel: 4.10.6
CPU: Inter Core i5-3230M
RAM: 11887MiB

The python script only import numpy , keras.

**Comment by roxma** [comment]
Which process? NCM is running from a different process, Do you mean that the memory usage of this process keeps growing?

**Comment by roxma** [comment]
It seems jedi library enters infinite loop after ```# foo.|``` is typed.

**Comment by roxma** [comment]
@theFool32 
I have similar issue with `# foo.` typed. I'm not sure whether it's the same issue as yours.

I've pushed some update. Hopefully it might also fix the issue.

**Comment by theFool32** [comment]
Sorry for not response in time.
What I meet is that `cm_sources.cm_jedi nvim-completion-manager` takes up 99% Memory.
It may happens after opening a python script and leaving it alone for a long time(maybe hours?) or just typing simple list variable like `p[`

What message could I get for you to debug if It shows up again?

**Comment by roxma** [comment]
The log files will be useful for trouble-shooting, put this into your vimrc would enable the logging of NCM.

```vim
let $NVIM_PYTHON_LOG_FILE='/path/logfile.log'
let $NVIM_NCM_LOG_LEVEL='DEBUG'
```

Maybe it's related to the settings of jedi library, I'm not quite sure, though.

**Comment by roxma** [comment]
If I can't fix this issue, I'll find a way to workaround it.

The NCM core process could simply kill the child process which takes too much memory, eg. 50% of system memory.

**Comment by roxma** [comment]
I'm not sure  how to reproduce this one.

But I've pushed a workaround, it sets the `RLIMIT_DATA` of jedi process to 1/3 of total  memory. The process will exit if it takes too much memory.

I closed this issue.

But it's open for further discussing.
