### ISSUE TITLE
Integrate with FZF for fuzzy search completion items?

### ISSUE THREAD

**Issue by roxma** [roxma/nvim-completion-manager#64]
Just read an interesting article https://nondev.io/Fuzzy-completion-in-Vim.

I personally don't like fuzzy completion all the time. But it seems useful to introduce another key, that start a FZF menu with current completion items for fuzzy search and completion.

**Comment by mrbiggfoot** [comment]
Is it possible to use fzf engine in the autocompletion popup window? That would be really great.

**Comment by roxma** [comment]
@mrbiggfoot 
It is possible. 

IMO probably it's not worth the effort. FZF is invoked by process call, and it may slow down the process.

Feel free to try you own implementation for matching/sorting, 

There is a small example: https://github.com/roxma/nvim-completion-manager/blob/master/pythonx/cm_matchers/prefix_matcher.py

**Comment by roxma** [comment]
This doesn't feels atractive any more. 

Closing.

A better option is to improve current fuzzy matching algorithms.
