### ISSUE TITLE
file path completion will always be triggered

### ISSUE THREAD

**Issue by jkunlin** [roxma/nvim-completion-manager#66]
path completion always in the completion list.

**Comment by roxma** [comment]
Could you provided more detailed information?

1. how to reproduce the unexpected behavior with minimal vimrc
2. screencast if possible
3. Log files generated via the instructions in this section: https://github.com/roxma/nvim-completion-manager#trouble-shooting

**Comment by jkunlin** [comment]
[
![ncm](https://cloud.githubusercontent.com/assets/3398363/24825222/fb7decac-1c4c-11e7-8459-00f57db22ede.png)
](url)
I create a directory containing abcde. Then I use vim to edit other file in this directory and type "abcd", and the path completion is shown. I think it will be better to trigger this completion only after typing "./" or something likes.

**Comment by roxma** [comment]
This is indended behavior.

If you really do want to override this, use a higher value of cm_refresh_min_word_len on the completion source. For example:

```
let g:cm_sources_override = {
    \ 'cm-filepath': {'cm_refresh_min_word_len': 100}
    \ }
```
