### ISSUE TITLE
New found lag when pressing tab and when waiting for options

### ISSUE THREAD

**Issue by partounian** [roxma/nvim-completion-manager#67]
Out of nowhere it seems that tab completion is slower now? I feel like I'm crazy, but all of sudden the autocomplete options are taking a bit long and pressing `Tab` takes a minute until it actually puts in the completed text. I tried it on a bunch of random files/buffers

It seems that any time I push `Tab` it calls `^I` as that is what is says on the bottom right.

(I have not changed anything in my zsh/nvim config in a few days and it was definitely fine before)

**Comment by roxma** [comment]
There's no big changes recently, It is always happenning?

What did you map the `<tab>` for?

I'll need a minimal vimrc for reproducing this issue. And a scrrentcast if it's possible.

**Comment by partounian** [comment]
I found the problem line
```
imap <expr> <Tab> (pumvisible() ? "\<C-n>" : (neosnippet#mappings#expand_or_jump_impl()!=''?neosnippet#mappings#expand_or_jump_impl():"\<Tab>"))
```
(this was copied from another issue) 

Though before testing this I tried it with neosnippet disabled but didn't see a difference until I simply commented this line.

**Comment by roxma** [comment]
If `neosnippet#mappings#expand_or_jump_impl()` is the cause you might need to open an issue on neosnippet.

**Comment by partounian** [comment]
His last commit was on Mar 31 (https://github.com/Shougo/neosnippet.vim/commits/master), so that's weird to have it appearing now. Anyhow, I'll just disable it and move on. Thanks!
