### ISSUE TITLE
This plugin and your paste-easy plugin don't work with vim-multiple-cursors.

### ISSUE THREAD

**Issue by partounian** [roxma/nvim-completion-manager#69]
Both plugins don't work with [multiple-cursors](https://github.com/terryma/vim-multiple-cursors). They both glitch in weird ways. 

This is with only paste-easy enabled. 
My actions were select each, delete, insert then I tried typing.
![This is the issue with only paste-easy enabled.](https://cloud.githubusercontent.com/assets/2541595/25164691/6fec0870-2487-11e7-9197-511498522a72.gif)

This is the issue with ncm and the plugins you saw above enabled.
![This is the issue with ncm and it's plugins enabled.](http://g.recordit.co/LAYStdoMVp.gif)

(I put the issues both here as I thought that would be better than duplication, if this was wrong of me, I will create another ticket for paste-easy.)

**Comment by roxma** [comment]
Duplicate issue https://github.com/roxma/nvim-completion-manager/issues/18

**Comment by partounian** [comment]
@roxma For paste-easy would it be better to call
`start_easy_paste /  stop_easy_paste`, or `PasteEasyDisable / PasteEasyEnable`
