### ISSUE TITLE
Support javascript blocks in jsx files

### ISSUE THREAD

**Issue by sassanh** [roxma/nvim-completion-manager#71]
Thanks for this great plugin.

Is it possible to support js blocks in jsx files? Something like this:
```
return <div onClick={() => {consol
```
It doesn't autocomplete `consol`

**Comment by roxma** [comment]
In your case, ncm will complete `console` if you have installed https://github.com/roxma/nvim-cm-tern

```javascript
return <div onClick={() => {consol
```
But ternjs cannot complete afeter `.` is pressed

```javascript
return <div onClick={() => {console.
```

![output](https://cloud.githubusercontent.com/assets/4538941/25732042/2b75edec-317e-11e7-8770-c16944dfec4b.gif)

------------------------------------------------------

I think this should be done with a ternjs plugin

I've found
https://github.com/jacksonrayhamilton/tern-jsx
https://github.com/angelozerr/tern-react
But unfortunately none of them works for me

**Comment by sassanh** [comment]
yeah, `console` works, but `console.` doesn't work. I close it as it you said it should be done by a tern plugin.
