### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by sassanh** [roxma/nvim-completion-manager#72]
I'm posting here to say thanks for implementing this fast and lightweight plugin. It solves the problems I had with YCM for years out of the box + It doesn't need compiling C++ files and installs in no time compared to YCM. I appreciate all the work they've done on YCM and deoplete but for my use cases ncm is much better auto completer specially considering how small and organized its code base is.

I can tweak things to better match my needs in ncm easily. I installed it 26 hours ago and with some minor tweaks it's doing auto completion for my Python, Javascript, C++ and VimL close to perfect. For example in half an hour I were able to use this great fuzzy search plugin: https://github.com/sergei-dyshel/vim-abbrev-matcher as my matcher.

Thanks

**Comment by roxma** [comment]
Glad to hear from you :smile:
