### ISSUE TITLE
Have JS using LanguageServer (as the one you already did for PHP) ?

### ISSUE THREAD

**Issue by charliesbox** [roxma/nvim-completion-manager#73]
Would be great to have that plugin instead of the tern one for javascript :)

**Comment by roxma** [comment]
[nvim-cm-tern](https://github.com/roxma/nvim-cm-tern) is not using LanguageServer. It's a wrapper for ternjs.

The php plugin I wrote almost did nothing. It's simply a php.vim and composer.json (like package.json in nodejs). The only reason for this plugin is for easier installation of the language server.

https://github.com/roxma/LanguageServer-php-neovim/blob/master/ftplugin/php.vim
https://github.com/roxma/LanguageServer-php-neovim/blob/master/composer.json

I think you may create simillar plugin for you own need.

**Comment by charliesbox** [comment]
oh, ok. Can I ask you further things about its implementation? I think I can do the same trick for javascript.

**Comment by roxma** [comment]
Sure, feel free to ask.

**Comment by roxma** [comment]
Close but open for futher discussion.
