### ISSUE TITLE
how to make merlin completion working?

### ISSUE THREAD

**Issue by wangsongiam** [roxma/nvim-completion-manager#77]
I've tried to add Ocaml's [merlin](https://github.com/ocaml/merlin) completion in NCM but couldn't make it. 

Yet I noticed Deoplete has a way to make it working already,  wonder how NCM could do it?
![screen shot 2017-05-22 at 5 27 43 pm](https://cloud.githubusercontent.com/assets/19645990/26329183/01b1fc0a-3f14-11e7-8d24-53f48c6e4121.png)

https://facebook.github.io/reason/tools.html

**Comment by roxma** [comment]
Refer to the css example in the [Configuration tips](https://github.com/roxma/nvim-completion-manager#configuration-tips) section
