### ISSUE TITLE
Annoying random \<Plug>(cm_completefunc) insertions

### ISSUE THREAD

**Issue by sassanh** [roxma/nvim-completion-manager#78]
Sometimes when I'm typing, suddenly a `\<Plug>(cm_completefunc)` is inserted. Sometimes when i press `:w` to write the file suddenly a `\<Plug>(cm_completefunc)` comes after w and as I press `<cr>` quickly after `:w` the file actually writes to `\<Plug>(cm_completefunc)`.
Does anyone else have this problem?

**Comment by roxma** [comment]
I have similar issue a few times. It occurs randomly.

Maybe there's a race condition. Or somehow in-compatible with another plugin by feeding keys  or modifying the buffer at the same time.

**Comment by sassanh** [comment]
What do you think about checking if vim is in normal mode before `call feedkeys(g:cm_completekeys)`?

**Comment by sassanh** [comment]
Can we avoid feedkeys altogether and use normal function call?

**Comment by roxma** [comment]
> What do you think about checking if vim is in normal mode before call feedkeys(g:cm_completekeys)?

I've just added the check: https://github.com/roxma/nvim-completion-manager/commit/025240dd4053a84610ba370234edb1e35e9a35fe


> Can we avoid feedkeys altogether and use normal function call?

It seems it's impossible for `omnifunc` and `completefunc`

**Comment by sassanh** [comment]
OK, I pulled those commits, lets see if it fixes the problem.

**Comment by roxma** [comment]
Closing.

Reopen if it's still happening.

**Comment by sassanh** [comment]
It seems to be solved.
