### ISSUE TITLE
flow support?

### ISSUE THREAD

**Issue by ahmedelgabri** [roxma/nvim-completion-manager#81]
Any plans to add [flow](https://flow.org/) support?

**Comment by charliesbox** [comment]
this would be awesome!

**Comment by davidosomething** [comment]
i believe you can do passthrough from deoplete-flow by adding both deoplete and deoplete-flow, and setting up deoplete as an nvim-completion-manager source

**Comment by ahmedelgabri** [comment]
> i believe you can do passthrough from deoplete-flow by adding both deoplete and deoplete-flow, and setting up deoplete as an nvim-completion-manager source

I'm actually trying nvim-completion-manager, because I had too many issues with deoplete.

**Comment by Shougo** [comment]
> I'm actually trying nvim-completion-manager, because I had too many issues with deoplete.

Interesting.

**Comment by ahmedelgabri** [comment]
@Shougo Just to be clear, maybe `deoplete` itself is not bad but the other completions are the problem. I had lots of problems with `deoplete-tern` for example.

While `nvim-completion-manager` & [`completor.vim`](https://github.com/maralla/completor.vim) they just work. So I'm trying all the options to see which one will work for me

**Comment by Shougo** [comment]
Ah, OK.
I recommend for you to use LSP typescript client.
It also supports javascript.

**Comment by charliesbox** [comment]
@Shougo that lsp server doesn't support flow. Actually, it shows errors everywhere cause flow is not a valid syntax

**Comment by Shougo** [comment]
LSP flow client is needed...

**Comment by roxma** [comment]
Closing

Further discussions should be posted at https://github.com/roxma/ncm-flow/issues/1

**Comment by tssm** [comment]
Actually Facebook is developing a [Flow language server](https://www.npmjs.com/package/flow-language-server).
