### ISSUE TITLE
ncm + gocode: cmd window is boring

### ISSUE THREAD

**Issue by jsfaint** [roxma/nvim-completion-manager#83]
I use neovim on windows with ncm.
When writing golang, the cmd window is flipping, which will impact the inputing.
![ncm-gocode](https://cloud.githubusercontent.com/assets/571829/26611938/1c80884a-45e4-11e7-8422-862454bcb0f6.gif)

neovim version
```
NVIM v0.2.1-25-g2e3b78d1
Build type: RelWithDebInfo
```

There is no this issue in gvim for windows , but the performance of gvim is a little bad..

**Comment by roxma** [comment]
Oh, Seems I have solved this before. Maybe it needs some extra code to hide the window.

I just switched all my PCs to linux. I'll check this later.

**Comment by jsfaint** [comment]
@roxma Thanks for your reply 😄 
My only windows environment is the working computer.
If you need any test or experiment just shoot it to me

**Comment by jsfaint** [comment]
I have a dirty fix on this issue, Does it acceptable? @roxma

**Comment by roxma** [comment]
I see.

I'll accept it if no better solution is found. Wait ultil next week. Or next/next week. (I get busy)

**Comment by jsfaint** [comment]
@roxma I'm just doing an experiment.
Don't be afraid, I'm not pushing you. 😄

**Comment by roxma** [comment]
I have a general purpose hack, please test the `widnows-popen-hack` branch

**Comment by jsfaint** [comment]
I'm on vacation now.
I will test it when I get back about 6/23

**Comment by jsfaint** [comment]
Tested on Windows, works for me 👍 Thanks
