### ISSUE TITLE
Leaves vim in a weird state if using ^C while showing completions

### ISSUE THREAD

**Issue by fortes** [roxma/nvim-completion-manager#87]
I'm getting some weird behavior after hitting `^C` when using this plugin. To repro:

1. Open any file.
2. Begin typing and wait for a completion to appear
3. Hit `^C` (control-c)
4. Hit `d`, which will now incorrectly delete the entire line

Using the following `init.vim` (with `vim-plug`) on nvim 0.1.7:

```
call plug#begin()
Plug 'roxma/nvim-completion-manager'
call plug#end()
```

This doesn't repro if I disable `nvim-completion-manager`.

**Comment by Shougo** [comment]
Same issue of https://github.com/Shougo/deoplete.nvim/issues/477.

**Comment by roxma** [comment]
Wired. I cannot reproduce this issue on my machine (with nvim v0.2.0)

You could use `<c-[>` (same as `<ESC>`) instead of `<c-c>`.

Or just map `<c-c>` to `<ESC>`

**Comment by fortes** [comment]
So is the lack of an InsertLeave event a bug in NeoVim?

**Comment by Shougo** [comment]
> So is the lack of an InsertLeave event when using <c-c> a bug in NeoVim?

No.  This is the feature of Vim/NeoVim.
Please read the documentation.

```vim
							*InsertLeave*
InsertLeave			When leaving Insert mode.  Also when using
				CTRL-O |i_CTRL-O|.  But not for |i_CTRL-C|.
```

**Comment by Shougo** [comment]
> So is the lack of an InsertLeave event when using <c-c> a bug in NeoVim?

No.  This is the feature of Vim/NeoVim.
Please read the documentation.

```vim
							*InsertLeave*
InsertLeave			When leaving Insert mode.  Also when using
				CTRL-O |i_CTRL-O|.  But not for |i_CTRL-C|.
```
