### ISSUE TITLE
Redetect sources on rtp change, support plugin manager's on demand loading

### ISSUE THREAD

**Issue by roxma** [roxma/nvim-completion-manager#98]
NCM detect sources at startup, asynchronously. This process does not hurt the performance.

But I just noticed that some users tend to use the plugin manager's on-demand loading,  `Plug 'foo', { 'for': 'filetype' }`. NCM will fail  loading the source when the buffer is opened after NCM have  started.

On-demand loading is still useful when the plugin contains both NCM source, and some other utilities.

So the solution should be: re-detect sources on `rtp` changed.

**Comment by roxma** [comment]
@jsfaint 

It works, for example, if you use `nvim foo.js` to open the file. It does not work, when you open nvim, then use `:e foo.js`  command to open the file.

**Comment by jsfaint** [comment]
Got it! I just know why the sources suddenly not works 😃 
Thanks!

**Comment by iamcco** [comment]
neco-vim source not works
----
nvim: v0.2.0
vimrc:
```
call plug#begin(expand('<sfile>:p:h') . '/plugged')
        Plug 'roxma/nvim-completion-manager'
        Plug 'Shougo/neco-vim',     { 'for': 'vim' }
call plug#end()
```

steps:
```
nvim test.md
:e test.vim
call sub
```
it works if change ` Plug 'Shougo/neco-vim',     { 'for': 'vim' }`  to ` Plug 'Shougo/neco-vim'`
